# Generated by Django 3.1.3 on 2020-11-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformationmodel',
            name='salary',
            field=models.CharField(max_length=200),
        ),
    ]
